# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transcriber.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11transcriber.proto\x12\x0btranscriber\"\x1d\n\x0cVideoRequest\x12\r\n\x05video\x18\x01 \x01(\x0c\"%\n\x0fTranscriptReply\x12\x12\n\ntranscript\x18\x01 \x01(\t2V\n\x0bTranscriber\x12G\n\nTranscribe\x12\x19.transcriber.VideoRequest\x1a\x1c.transcriber.TranscriptReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transcriber_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VIDEOREQUEST._serialized_start=34
  _VIDEOREQUEST._serialized_end=63
  _TRANSCRIPTREPLY._serialized_start=65
  _TRANSCRIPTREPLY._serialized_end=102
  _TRANSCRIBER._serialized_start=104
  _TRANSCRIBER._serialized_end=190
# @@protoc_insertion_point(module_scope)

