apiVersion: v1
kind: Service
metadata:
  name: recon-server
spec:
  selector:
    app: recon-server
  ports:
  - name: http
    port: 80
    targetPort: 8000
  - name: grpc
    port: 50051
    targetPort: 50051
  type: ClusterIP

