# Domain-Adversarial Neural Network training example

dataset:
  h5_file: data/data.h5
  features_h5: data/features.h5
  csv_file: data/labels.csv
  domain_csv: data/domains.csv
  vocab: vocab.txt

checkpoints:
  dir: checkpoints
  teacher_ckpt: null

model:
  arch: stgcn

hyperparameters:
  epochs: 10
  batch_size: 4
  seq_len: 16
  max_seq_len: 128
  learning_rate: 0.001
  adversarial: true
  adv_mix_rate: 0.5
  adv_weight: 0.1
  adv_steps: 1
