pose:
  count: 33
  connections:
    - [0,1]
    - [1,2]
    - [2,3]
    - [3,7]
    - [0,4]
    - [4,5]
    - [5,6]
    - [6,8]
    - [9,10]
    - [11,12]
    - [11,13]
    - [13,15]
    - [15,17]
    - [15,19]
    - [15,21]
    - [17,19]
    - [12,14]
    - [14,16]
    - [16,18]
    - [16,20]
    - [16,22]
    - [18,20]
    - [11,23]
    - [12,24]
    - [23,24]
    - [23,25]
    - [24,26]
    - [25,27]
    - [26,28]
    - [27,29]
    - [28,30]
    - [29,31]
    - [30,32]
    - [27,31]
    - [28,32]
left_hand:
  count: 21
  connections: &hand_conn
    - [0,1]
    - [1,2]
    - [2,3]
    - [3,4]
    - [0,5]
    - [5,6]
    - [6,7]
    - [7,8]
    - [5,9]
    - [9,10]
    - [10,11]
    - [11,12]
    - [9,13]
    - [13,14]
    - [14,15]
    - [15,16]
    - [13,17]
    - [17,18]
    - [18,19]
    - [19,20]
    - [0,17]
right_hand:
  count: 21
  connections: *hand_conn
face:
  count: 468
  connections: []
flow:
  count: 1
  connections: []
